#include "hal_data.h"

FSP_CPP_HEADER
void R_BSP_WarmStart(bsp_warm_start_event_t event);
void Uart0_Transmit();
uint32_t SysTick_GetTick(void);
void SysTick_Handler();
FSP_CPP_FOOTER

#define TRANSFER_LENGTH 128

volatile uint32_t u32Systick = 0;
volatile uint32_t u32Tick1s = 0;
volatile uint32_t u32Tick1m = 0;

volatile uint32_t state_led = 0;
volatile uint32_t u32Uart0TxDoneFlag = 0;
volatile uint32_t u32Uart4TxDoneFlag = 0;
uint8_t u8BufferUart0Rx[128] = {0};
uint8_t u8BufferUart4Rx[128] = {0};
uint8_t u8SW1State = 0;
uint32_t SysTick_GetTick(void) {
    return u32Systick;
}

void SysTick_Handler()
{
    u32Systick++;
    u32Tick1s++;
    u32Tick1m++;
}

void user_uart_callback(uart_callback_args_t *p_args) {
    if(p_args->channel == 0) {
        if(p_args->event == UART_EVENT_RX_COMPLETE) {
            g_uart0.p_api->read(g_uart0.p_ctrl, u8BufferUart0Rx, 128);
        } else if(p_args->event == UART_EVENT_TX_COMPLETE) {
            u32Uart0TxDoneFlag = 1;
        }
    } else if(p_args->channel == 4) {
        if(p_args->event == UART_EVENT_RX_COMPLETE) {
            g_uart4.p_api->read(g_uart4.p_ctrl, u8BufferUart4Rx, 128);
        } else if(p_args->event == UART_EVENT_TX_COMPLETE) {
            u32Uart4TxDoneFlag = 1;
        }
    }
}

void Uart0_Transmit(uint8_t * pu8Data, uint32_t u32Length, uint32_t u32TimeOut) {
    u32Uart0TxDoneFlag = 0;
    uint32_t tickStart = SysTick_GetTick();
    g_uart0.p_api->write(g_uart0.p_ctrl, pu8Data, u32Length);
    while(!u32Uart0TxDoneFlag) {
        if((SysTick_GetTick() - tickStart) >= u32TimeOut) {
            break;
        }
    }
}

typedef void (*key_callback_t)(void);

key_callback_t key_callback = NULL;

void callback1(void)
{
    Uart0_Transmit("callback1\r\n" , 11, 1000);
    g_ioport.p_api->pinWrite(g_ioport.p_ctrl,LED1,1);
    g_ioport.p_api->pinWrite(g_ioport.p_ctrl,LED2,0);

}

void callback2(void)
{
    Uart0_Transmit("callback2\r\n" , 11, 3000);
    g_ioport.p_api->pinWrite(g_ioport.p_ctrl,LED1,0);
    g_ioport.p_api->pinWrite(g_ioport.p_ctrl,LED2,1);
}

void callback3(void)
{
    Uart0_Transmit("callback3\r\n" , 11, 3000);
}


/*******************************************************************************************************************//**
 * main() is generated by the RA Configuration editor and is used to generate threads if an RTOS is used.  This function
 * is called by main() when no RTOS is used.
 **********************************************************************************************************************/
void hal_entry(void)
{
    /* TODO: add your own code here */

    // Step 1: Init systick
    SysTick_Config(SystemCoreClock / 1000);
    // Step 2: Init peripheral
    g_uart0.p_api->open(g_uart0.p_ctrl, g_uart0.p_cfg); // khoi tao UART
    g_uart0.p_api->read(g_uart0.p_ctrl, u8BufferUart0Rx, 128); // Tro du lieu nhan duoc den buffer

    g_uart4.p_api->open(g_uart4.p_ctrl, g_uart4.p_cfg); // khoi tao UART
    g_uart4.p_api->read(g_uart4.p_ctrl, u8BufferUart4Rx, 128); // Tro du lieu nhan duoc den buffer


    while(1){
        if(u32Tick1m >= 1) {
            u32Tick1m = 0;

            g_ioport.p_api->pinRead(g_ioport.p_ctrl, SW1, &u8SW1State);
            if(!u8SW1State) {
                if(key_callback != NULL) {
                    key_callback();
                }
                while(!u8SW1State){
                    g_ioport.p_api->pinRead(g_ioport.p_ctrl, SW1, &u8SW1State);
                }
            }
        }

        if(u32Tick1s >= 1000) {
            u32Tick1s = 0;

            state_led = state_led ? 0: 1;

            if(strstr(u8BufferUart0Rx, "callback1")) {
                key_callback = callback1;
                memset(u8BufferUart0Rx, 0x00, 128); // clear buffer
                g_uart0.p_api->read(g_uart0.p_ctrl, u8BufferUart0Rx, 128);
                //R_SCI_UART_Read(&g_uart0_ctrl, u8BufferUart0Rx, TRANSFER_LENGTH);
            } else if(strstr(u8BufferUart0Rx, "callback2")) {
                key_callback = callback2;
                memset(u8BufferUart0Rx, 0x00, 128);
                g_uart0.p_api->read(g_uart0.p_ctrl, u8BufferUart0Rx, 128);
            } else if(strstr(u8BufferUart0Rx, "callback3")) {
                key_callback = callback3;
                memset(u8BufferUart0Rx, 0x00, 128);
                g_uart0.p_api->read(g_uart0.p_ctrl, u8BufferUart0Rx, 128);
            } else if(strstr(u8BufferUart0Rx, "clear")) {
                key_callback = NULL;
                memset(u8BufferUart0Rx, 0x00, 128);
               g_uart0.p_api->read(g_uart0.p_ctrl, u8BufferUart0Rx, 128);
            }

            //g_ioport.p_api->pinWrite(g_ioport.p_ctrl, LED1, state_led);

            //Uart0_Transmit("12345678\r\n" , 10, 3000);
        }
    }

#if BSP_TZ_SECURE_BUILD
    /* Enter non-secure code */
    R_BSP_NonSecureEnter();
#endif
}

/*******************************************************************************************************************//**
 * This function is called at various points during the startup process.  This implementation uses the event that is
 * called right before main() to set up the pins.
 *
 * @param[in]  event    Where at in the start up process the code is currently at
 **********************************************************************************************************************/
void R_BSP_WarmStart(bsp_warm_start_event_t event)
{
    if (BSP_WARM_START_RESET == event)
    {
#if BSP_FEATURE_FLASH_LP_VERSION != 0

        /* Enable reading from data flash. */
        R_FACI_LP->DFLCTL = 1U;

        /* Would normally have to wait tDSTOP(6us) for data flash recovery. Placing the enable here, before clock and
         * C runtime initialization, should negate the need for a delay since the initialization will typically take more than 6us. */
#endif
    }

    if (BSP_WARM_START_POST_C == event)
    {
        /* C runtime environment and system clocks are setup. */

        /* Configure pins. */
        R_IOPORT_Open (&g_ioport_ctrl, g_ioport.p_cfg);
    }
}

#if BSP_TZ_SECURE_BUILD

BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ();

/* Trustzone Secure Projects require at least one nonsecure callable function in order to build (Remove this if it is not required to build). */
BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ()
{

}
#endif
